meeting_scheduler/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scheduler.urls')),
    path('user/', include('users.urls')),
    path('meeting/', include('meetings.urls'))

]

meetings/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from .views import MeetingsListView, MeetingDetailView, MeetingCreate, MeetingUpdate, MeetingDelete, MeetingInvite, NotificationListView, MeetingMessage

urlpatterns = [
    path('', MeetingsListView.as_view(), name='meetings_view'),
    path('notifications/', NotificationListView.as_view(), name='notifications_view'),
    path('create/', MeetingCreate.as_view(), name='create_view'),
    path('<int:pk>/', MeetingDetailView.as_view(), name='meeting_view'),
    path('<int:mid>/invite/', MeetingInvite.as_view(), name='invite_view'),
    path('<int:pk>/edit/', MeetingUpdate.as_view(), name='meeting_update_view'),
    path('<int:pk>/delete/', MeetingDelete.as_view(), name='meeting_delete_view'),
    path('<int:mid>/cancel/<username>/', views.cancel_invite, name='cancel_invite'),
    path('<int:mid>/accept/', views.accept_invite, name='accept_invite'),
    path('<int:mid>/decline/', views.decline_invite, name='decline_invite'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('login/', views.user_login, name='login_view'),
	path('register/', views.register, name='register_view'),
	path('profile/', views.profile, name='profile_view'),
	path('logout/', views.user_logout, name='logout_view'),
	path('edit/', views.profile_edit, name='profile_edit_view')
]

meetings/models.py
from django.db import models
from users.models import User
from django.utils import timezone


class Meeting(models.Model):
	mid = models.AutoField(primary_key=True)
	title = models.CharField(max_length=50, blank=False)
	start_time = models.DateTimeField()
	end_time = models.DateTimeField(blank=False)
	create_time = models.DateTimeField(auto_now_add=True)
	last_edit_time = models.DateTimeField(auto_now=True)
	desc = models.TextField(max_length=500, blank=False)
	location = models.TextField(max_length=500, blank=False)
	city = models.CharField(max_length=50, blank=False)
	creator = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
	status = models.BooleanField(default=True)

	def __str__(self):
		return f'{self.mid} - {self.title}'

	def delete(self, *args, **kwargs):
		self.status = False
		self.save()
		meetingaction = MeetingAction.objects.create()
		meetingaction.meeting = self
		meetingaction.action = 5
		meetingaction.sender = self.creator
		for accepted in MeetingAction.objects.filter(meeting=self,
													 action=2):
			meetingaction.pk = None
			meetingaction.reciever = accepted.sender
			meetingaction.save()


ACTION_CHOICES = [
	(1, 'invited you to attend'),
	(2, 'has accepted your invite to'),
	(3, 'cannot attend'),
	(4, 'sent you a personal message regarding '),
	(5, 'cancelled the event')
]


class MeetingAction(models.Model):
	meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE, null=True)
	sender = models.ForeignKey(
		User, on_delete=models.CASCADE, null=True, related_name='sender')
	reciever = models.ForeignKey(
		User, on_delete=models.CASCADE, null=True, related_name='reciever')
	action = models.SmallIntegerField(null=True, choices=ACTION_CHOICES)
	message = models.TextField(max_length=500, blank=False)
	decision_time = models.DateTimeField(auto_now=True)

	def __str__(self):
		return f'o' or ''

meetings/forms.py
from django import forms
from .models import Meeting, MeetingAction

class MeetingUpdateForm(forms.ModelForm):
    class Meta:
        model = Meeting
        fields = ('title', 'desc', 'start_time', 'end_time', 'location', 'city')


class MeetingInviteForm(forms.ModelForm):
    class Meta:
        model = MeetingAction
        fields = ('message',)

meetings/views.py
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from .models import Meeting, MeetingAction
from users.models import User
from .forms import MeetingUpdateForm, MeetingInviteForm
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.contrib import messages
from django.db.models import Q
from operator import attrgetter


class MeetingsListView(ListView):
    model = Meeting

    def get_context_data(self, **kwargs):
        context = super(MeetingsListView, self).get_context_data(**kwargs)

        accepted_meetings = set()
        try:
            for meeting in Meeting.objects.filter(creator=self.request.user, status=True):
                accepted_meetings.add(meeting)
            for meeting in MeetingAction.objects.filter(sender=self.request.user, action=2):
                if(meeting.meeting.status):
                    accepted_meetings.add(meeting.meeting)

            context['meetings'] = sorted(
                accepted_meetings, key=attrgetter('start_time'))
        except:
            pass
        return context


class NotificationListView(ListView):
    model = Meeting
    template_name = 'meetings/meetingaction_list.html'

    def get_context_data(self, **kwargs):
        context = super(NotificationListView, self).get_context_data(**kwargs)
        try:
            context['active_notifications'] = MeetingAction.objects.filter(Q(reciever=self.request.user) & Q(
                decision_time__gte=self.request.user.profile.last_notif_check)).order_by('-decision_time')
        except:
            context['active_notifications'] = None

        try:
            context['seen_notifications'] = MeetingAction.objects.filter(Q(reciever=self.request.user) & Q(
                 decision_time__lt=self.request.user.profile.last_notif_check)).order_by('-decision_time')
        except:
            context['seen_notifications'] = None
        
        self.request.user.profile.save()
        return context


class MeetingDetailView(DetailView):
    model = Meeting
    context_object_name = 'meeting'

    def get_context_data(self, **kwargs):
        context = super(MeetingDetailView, self).get_context_data(**kwargs)
        meeting = self.get_object()
        
        try:
            meetingaction = MeetingAction.objects.filter(Q(meeting=meeting) & (
                Q(reciever=self.request.user) | Q(sender=self.request.user)) & ~Q(action=4)).latest('decision_time')
        except MeetingAction.DoesNotExist:
            meetingaction = None

        try:
            context['participants'] = MeetingAction.objects.filter(meeting=meeting, action=2)
        except MeetingAction.DoesNotExist:
            pass
        
        try:
            context['invites'] = MeetingAction.objects.filter(meeting=meeting, action=1)
        except MeetingAction.DoesNotExist:
            pass
            
        try:
            context['declines'] = MeetingAction.objects.filter(meeting=meeting, action=3)
        except MeetingAction.DoesNotExist:
            pass

        if meeting.creator == self.request.user:
            context['perm_level'] = 0
        elif meetingaction:
            context['perm_level'] = meetingaction.action

        return context


class MeetingCreate(CreateView):
    model = Meeting
    form_class = MeetingUpdateForm

    def get_initial(self, *args, **kwargs):
        initial = super(MeetingCreate, self).get_initial(*args, **kwargs)
        initial['location'] = self.request.user.profile.location
        initial['city'] = self.request.user.profile.city
        return initial

    def form_valid(self, form):
        self.meeting = form.save(commit=False)
        self.meeting.creator = self.request.user
        self.meeting.save()
        messages.success(self.request, "Meeting created")
        return redirect('meeting_view', pk=self.meeting.pk)


class MeetingUpdate(UpdateView):
    model = Meeting
    form_class = MeetingUpdateForm

    def form_valid(self, form):
        self.meeting = form.save(commit=False)
        self.meeting.last_edit_time = timezone.now()
        self.meeting.save()

        messages.success(self.request, "Meeting updated")
        return redirect('meeting_view', pk=self.meeting.pk)


class MeetingDelete(DeleteView):
    model = Meeting
    success_url = reverse_lazy('meetings_view')
    context_object_name = 'meeting'


class MeetingInvite(FormView):
    form_class = MeetingInviteForm
    template_name = 'meetings/meeting_invite.html'

    def form_valid(self, form):
        userslist = self.request.POST.get('inviteelist').split(',')
        meetingaction = form.save(commit=False)

        meetingaction.meeting = Meeting.objects.get(mid=self.kwargs['mid'])
        meetingaction.action = 1
        meetingaction.sender = self.request.user

        print(self.request.POST.get('inviteelist'))

        for user in userslist:
            meetingaction.pk = None
            try:
                meetingaction.reciever = User.objects.get(username=user)
                meetingaction.save()
            except:
                continue

        return redirect('meeting_view', pk=self.kwargs['mid'])

    def get_context_data(self, *args, **kwargs):
        context = super(MeetingInvite, self).get_context_data(**kwargs)
        context['users'] = User.objects.all()
        return context


class MeetingMessage(FormView):
    form_class = MeetingInviteForm
    template_name = 'meetings/meeting_message.html'

    def form_valid(self, form):
        meetingaction = form.save(commit=False)
        meetingaction.action = 4
        meetingaction.meeting = Meeting.objects.get(mid=self.kwargs['mid'])
        meetingaction.reciever = meetingaction.meeting.creator
        meetingaction.sender = self.request.user
        meetingaction.save()

        return redirect('meeting_view', pk=self.kwargs['mid'])

def accept_invite(request, mid):
    meetingaction = MeetingAction.objects.filter(
        meeting=mid, reciever=request.user).latest('decision_time')
    if(meetingaction.action == 1):
        meetingaction.reciever, meetingaction.sender = meetingaction.sender, meetingaction.reciever
        meetingaction.action = 2
        meetingaction.save()

        return redirect('meeting_view', pk=mid)


def decline_invite(request, mid):
    meetingaction = MeetingAction.objects.filter(Q(meeting=mid) & (
        Q(reciever=request.user) | Q(sender=request.user))).latest('decision_time')
    if(meetingaction.action == 1 or meetingaction.action == 2):
        if(meetingaction.action == 1):
            meetingaction.sender, meetingaction.reciever = meetingaction.reciever, meetingaction.sender
        meetingaction.action = 3
        meetingaction.save()

        return redirect('meeting_view', pk=mid)


def cancel_invite(request, mid, username):
    user = User.objects.get(username=username)
    MeetingAction.objects.get(meeting=mid, reciever=user, action=1).delete()
    return redirect('meeting_view', pk=mid) 

meetings/templates/meetings/meeting_confirm_delete.html
{% extends 'scheduler/detail.html' %}

{% block title %} Delete Meeting {% endblock %}
{% block desc %} Are you sure you want to delete {{ meeting.title }}? {% endblock %}

{% block main %}
	<form method="POST">
		{% csrf_token %}
		Message:<br/>
		<textarea cols="40" rows="10" name="message">
		</textarea><br>
		<button type="submit" class="btn btn-danger">
			<span class="material-icons mx-2">delete</span>
			Delete
		</button>

		<a href="{% url 'meeting_view' meeting.mid %}">
			<button class="btn">
				<span class="material-icons mx-2">cancel</span>
				Cancel
			</button>
		</a>
	</form>
{% endblock %}

meetings/templates/meetings/meeting_detail.html
{% extends 'scheduler/detail.html' %}

{% block title %} {{ meeting.title }} {% endblock %}
{% block main %}
		{% for message in messages %}
			<p class="message alert-success alert">{{ message }}</p>
		{% endfor %}
		<span class="tag font-weight-bold">Location</span><br/>
		<span class="value">{{ meeting.location }}</span><br/><br/>


		<span class="tag font-weight-bold">City</span><br/>
		<span class="value">{{ meeting.city }}</span><br/><br/>


		<span class="tag font-weight-bold">Description</span><br/>
		<span class="value">{{ meeting.desc }}</span><br/><br/>

		{% if participants %}
		<span class="tag font-weight-bold">Participants</span><br/>
		<span class="value">
			{% for participant in participants %}
				{{ participant.sender.first_name }} {{ participant.sender.last_name }} ({{ participant.sender }}), 
			{% endfor %}
		</span><br/><br/>
		{% endif %}

		{% if perm_level == 0 %}

			{% if declines %}
			<span class="tag font-weight-bold">Declined</span><br/>
			<span class="value">
				{% for participant in declines %}
					{{ participant.sender.first_name }} {{ participant.sender.last_name }} ({{ participant.sender }}), 
				{% endfor %}
			</span><br/><br/>
			{% endif %}

			{% if invites %}
			<span class="tag font-weight-bold">Invitees</span><br/>
			<span class="value">
				{% for participant in invites %}
				{{ participant.reciever.first_name }} {{ participant.reciever.last_name }} ({{ participant.reciever }})
				<small><a href="{% url 'cancel_invite' meeting.mid participant.reciever.username %}"> Cancel invite </a></small>, 
				{% endfor %}
			</span><br/><br/>
			{% endif %}
		{% endif %}

		<span class="tag font-weight-bold">Time</span><br/>
		<span class="value">From {{ meeting.start_time }} to {{ meeting.end_time }}</span><br/><br/>

		<span class="tag font-weight-bold">Created By</span><br/>
		<span class="value">

			{% if meeting.creator.username == user.username %}
				You
			{% else %}
				{{ meeting.creator.first_name }} {{ meeting.creator.last_name }} ({{ meeting.creator.username }})
			{% endif %}
		</span><br/><br/>

		{% if not meeting.status %}
		<p class="message alert-danger alert">This event has been cancelled or finished</p>
		{% else %}
		{% if perm_level == 0 %}
			<a href="{% url 'meeting_update_view' meeting.mid %}">

			<button class="btn">
				<span class="material-icons mx-2">edit</span>
				Edit
			</button>
			</a>

			<a href="{% url 'meeting_delete_view' meeting.mid %}">
				<button class="btn bg-danger">
				<span class="material-icons mx-2">delete</span>
				Delete
			</button>
			</a>

			<a href="{% url 'invite_view' meeting.mid %}">

				<button class="btn">
					<span class="material-icons mx-2">add</span>
					Invite
				</button>
				</a>
		{% elif perm_level == 1 %}

		<p class="alert">You are invited to this meeting</p>
		<a href="{% url 'accept_invite' meeting.mid %}">

			<button class="btn">
				<span class="material-icons mx-2">check</span>
				Accept
			</button>
			</a>

			<a href="{% url 'decline_invite' meeting.mid %}">
				<button class="btn bg-danger">
				<span class="material-icons mx-2">cancel</span>
				Cancel
			</button>
			</a>

			{% elif perm_level == 2 %}
			<p class="alert alert-success">You are attending this meeting</p>
			<a href="{% url 'decline_invite' meeting.mid %}">
				<button class="btn bg-danger">
				<span class="material-icons mx-2">cancel</span>
				Cancel
			</button>

			<a href="{% url 'message_view' meeting.mid %}">
				<button class="btn bg-danger">
				<span class="material-icons mx-2">send</span>
				Send a Message
			</button>
			</a>
			</a>
		
			{% elif perm_level == 3 %}
			<p class="alert alert-danger">You declined invitation to this meeting</p>
		{% endif %}

			


		{% endif %}
	</div>
	
</div>

{% endblock %}

meetings/templates/meetings/meeting_form.html
{% extends 'scheduler/detail.html' %}

{% block title %} New Meeting {% endblock %}

{% block main %}
	<form method="POST">
		{% csrf_token %}
		{% for field in form %}
			{{ field.label_tag }}<br/>
			{{ field }}<br/>
			<p class="errors">{{ field.errors }}</p>
		{% endfor %}
		<button type="submit" class="btn">
			<span class="material-icons mx-2">check</span>
			Save
		</button>
	</form>
{% endblock %}

meetings/templates/meetings/meeting_invite.html
{% extends 'scheduler/detail.html' %}

{% block title %} Invite People {% endblock %}
{% block desc %} Invite people to the meeting {% endblock %}

{% block main %}
	<form method="POST">
		{% csrf_token %}
		{% for field in form %}
			{{ field.label_tag }}<br/>
			{{ field }}<br/>
			<p class="errors">{{ field.errors }}</p>
		{% endfor %}

		People: <br/>
		<input list="users" id="user-input">
		<button class="btn" id="add-btn"><span class="material-icons">add</span></button>
		<br/><br/>

		<datalist id="users">
			{% for user in users %}
				<option value="{{user.username}}" data-id="{{ user.username }}">
			{% endfor %}
		</datalist>

		<p class="invitees" id="invitees"></p>
		<input type="hidden" name="inviteelist" id="inviteelist" value="">
		
		<button type="submit" class="btn">
			<span class="material-icons mx-2">check</span>
			Invite
		</button>

	</form>
{% endblock %}

{% block imports %}
	<script>
		const inputelem = document.getElementById("inviteelist")
		const btn = document.getElementById("add-btn")
		const userlist = document.getElementById("invitees")
		const username = document.getElementById("user-input")
		btn.onclick = (e) => {
			e.preventDefault();
			inputelem.value += username.value+","
			userlist.innerText += username.value+ ", "
			username.value = ""
		}

	</script>
{% endblock %}

meetings/templates/meetings/meeting_list.html
{% extends 'scheduler/base.html' %}

{% block content %}
<div class="row my-5">
	<h1 class="cols-lg-8 mx-3">Meetings</h1>
	<div class="cols-lg-2 my-auto ml-auto mx-3">
		<a href="{% url 'create_view' %}">
			<button class="btn">
			<span class="material-icons">
				add
			</span>
			New Meeting
		</button>
		</a>
		
	</div>
</div>
<div class="row">
	<table class="table table-striped">
		<thead>
		  <tr>
			<th scope="col">Meeting</th>
			<th scope="col">Venue</th>
			<th scope="col">Start Time</th>
			<th scope="col">End Time</th>
		  </tr>
		</thead>
		<tbody>
		  {% for meeting in meetings %}
			<tr>
				<td scope="col"><a href="{% url 'meeting_view' meeting.mid %}"> {{ meeting.title }}</a></td>
				<td scope="col">{{ meeting.location }}<br/>
				{{ meeting.city }}</td>
				<td scope="col">{{ meeting.start_time }}</td>
				<td scope="col">{{ meeting.end_time }}</td>
			</tr>
			{% endfor %}
		</tbody>
	  </table>
</div>

{% endblock %}

meetings/templates/meetings/meetingaction_list.html
{% extends 'scheduler/base.html' %}

{% block content %}
	<div class="row my-5">
		<h1 class="cols-lg-8 mx-3">Notifications</h1>
	</div>
	<div class="row">
		<table class="table table-striped">
			<tbody>
				<tr>
					<td> <b>Notifications</b> </td>
				</tr>
				{% for notification in seen_notifications %}
					<tr>
						<td class="text_weight_bold">{{ notification.sender }} {{ notification.get_action_display }} <a
								href="{% url 'meeting_view' notification.meeting.mid %}">{{ notification.meeting.title }}</a>
							{% if notification.action < 3 %} with the following message:<br>{% endif %}
							<blockquote>{{ notification.message }}</blockquote><br />
							<p class="small">{{ notification.decision_time }}</p>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
{% endblock %}